#
# Shows how to extract arrays and map from complex data structure
#
# blog: https://fabianlee.org/2021/11/12/ansible-extracting-a-list-or-dictionary-from-a-complex-data-structure/
#
#
# ansible-playbook datastructure-to-dict.yml
# 
# json_query filter requires 'community.general' galaxy module and jmespath pip module
#   pip3 install jmespath
#   ansible-galaxy collection install community.general
#
---
- hosts: all
  become: no
  gather_facts: no
  connection: local

  vars:
    # emulates structure of 'stat' module output (checks for file existence)
    # as test for pulling values out of deeply nested json structure
    my_json_structure:
      results:
        - item: /tmp/a.txt
          stat:
            exists: true
        - item: /tmp/b.txt
          stat:
            exists: false
        - item: /tmp/c.txt
          stat:
            exists: true

  tasks:

    # 'my_json_structure' emulates what 'stat' and 'with_fileglob' return
    #- stat:
    #    path: "{{item}}"
    #  register: complex_results
    #  with_fileglob: "/tmp/*"
    #- debug: msg="{{complex_results}}"

    # pulling single value out of each item, create list
    - set_fact:
        exist_list: "{{ ( my_json_structure.results | map(attribute='item') )  }}"
    - debug: msg="{{ exist_list }}"

    # pulling single value out of each item, create map
    - set_fact:
        exist_map_simple: "{{ dict( exist_list | zip(exist_list) ) }}"
    - debug: msg="{{ exist_map_simple }}"

    # pulling two values out of each item, create map with key/value
    - set_fact:
        exist_map: "{{ exist_map|default({}) | combine( {item.item : item.stat.exists} ) }}"
      with_items: "{{ my_json_structure | json_query('results[*]') }}"
    - debug: msg="{{ exist_map }}"
   
